import {db,money,esc,uid,audit} from './core.js';
import {day,outstanding,returnedQty,returnQuote,recordReturn,collectCredit,profitReport,reorderRows,parseVoice,supplierComparisons} from './commerce.js';
import {download} from './receipts.js';
const $=s=>document.querySelector(s),btn=(label,action,attrs='')=>`<button type="button" class="btn" data-biz="${action}" ${attrs}>${label}</button>`;
const field=(label,name,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
let ctx;
export async function pinDigest(pin,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:120000,hash:'SHA-256'},key,256);return Array.from(new Uint8Array(bits),x=>x.toString(16).padStart(2,'0')).join('')}
export async function managerApproval(reason){const auth=(await db.settings.get('manager-lock'))?.value;if(!auth)return true;return new Promise(resolve=>{
 const gate=document.createElement('dialog');gate.className='approval-dialog';gate.innerHTML=`<div class="modal-head"><h2>Manager approval</h2></div><form class="modal-body"><p class="help">${esc(reason)}</p>${field('Manager PIN','pin','','password','required inputmode="numeric" autocomplete="off"')}<p role="alert"></p><div class="modal-actions"><button type="button" class="btn">Cancel</button><button class="btn primary">Approve</button></div></form>`;document.body.append(gate);const finish=v=>{gate.close();gate.remove();resolve(v)};gate.querySelector('button[type=button]').onclick=()=>finish(false);gate.oncancel=e=>{e.preventDefault();finish(false)};gate.querySelector('form').onsubmit=async e=>{e.preventDefault();e.stopPropagation();const hold=+(sessionStorage.getItem('pin-wait')||0);if(Date.now()<hold){gate.querySelector('[role=alert]').textContent='Too many attempts. Wait one minute.';return}const input=gate.querySelector('input');if(await pinDigest(input.value,auth.salt)===auth.hash){sessionStorage.removeItem('pin-fails');finish(true)}else{const attempts=+(sessionStorage.getItem('pin-fails')||0)+1;sessionStorage.setItem('pin-fails',attempts);if(attempts>=5){sessionStorage.setItem('pin-wait',Date.now()+60000);sessionStorage.setItem('pin-fails',0)}input.value='';gate.querySelector('[role=alert]').textContent='Incorrect PIN.'}};gate.showModal();gate.querySelector('input').focus();
 })}
export function setupBusiness(context){ctx=context;let queue=Promise.resolve();document.addEventListener('click',e=>{const el=e.target.closest('[data-biz]');if(!el||el.disabled)return;queue=queue.then(()=>action(el.dataset.biz,el)).catch(e=>ctx.toast(e.message,true))});document.addEventListener('submit',e=>{if(!e.target.matches('[data-biz-form]'))return;e.preventDefault();const form=e.target;queue=queue.then(async()=>{if(!form.reportValidity())return;const button=form.querySelector('button[type=submit],button:not([type])');if(button)button.disabled=true;try{await submit(form.dataset.bizForm,Object.fromEntries(new FormData(form)),form)}finally{if(button)button.disabled=false}}).catch(e=>ctx.toast(e.message,true))});}
const modal=(title,html)=>ctx.modal(title,html);
export async function businessHub(){modal('Business tools',`<p class="help mb-4">Purchasing, profit, customers and checkout tools.</p><div class="business-grid">${[['reports','Profit & Explain my day'],['suppliers','Supplier price watch'],['reorder','Smart reorder basket'],['credit','Customer credit ledger'],['returns','Returns & exchanges'],['voice','Voice-assisted billing'],['labels','Shelf price labels'],['display','Customer display'],['identity','Business & tax details'],['security','Cashier & manager PIN'],['network','Receipt QR connection']].map(([action,label])=>btn(label,action)).join('')}</div>`)}
async function action(a,el){
 if(a==='hub')return businessHub();
 if(a==='reports'){const all=await db.sales.toArray(),today=day(),y=new Date();y.setDate(y.getDate()-1);const r=profitReport(all,today),prior=profitReport(all,day(y));modal('Profit & Explain my day',`<div class="stat-grid">${[['Sales before tax',r.revenue],['Product cost',r.cost],['Gross profit',r.profit],['Discounts',r.discounts]].map(([l,n])=>`<div class="panel"><small>${l}</small><h2>${money(n)}</h2></div>`).join('')}</div><div class="notice mt-4">${r.bills} completed bills today. Revenue is ${money(Math.abs(r.revenue-prior.revenue))} ${r.revenue>=prior.revenue?'higher':'lower'} than yesterday. Gross profit is ${money(Math.abs(r.profit-prior.profit))} ${r.profit>=prior.profit?'higher':'lower'}. Discounts total ${money(r.discounts)}; returns recorded today total ${money(r.returns)}.</div><p class="help mt-4">Calculated from saved sales, purchase costs at sale time, discounts and dated returns. Gross profit excludes operating expenses. Credit sales count as revenue even before collection. No invented AI explanations.</p>${btn('Export supporting figures','report-export')}`);return}
 if(a==='report-export'){const sales=await db.sales.toArray();download('speedbill-profit-'+day()+'.json',JSON.stringify({date:day(),...profitReport(sales,day()),saleIds:sales.filter(s=>day(s.created)===day()).map(s=>s.id)},null,2));return}
 if(a==='credit'){const sales=(await db.sales.toArray()).filter(s=>outstanding(s)>0&&s.status==='completed');modal('Customer credit ledger',`<p class="help mb-4">Outstanding balances, part payments, and customer payment history.</p>${sales.map(s=>`<div class="list-row"><div><strong>${esc(s.customer)}</strong><small>${esc(s.id)} · ${s.collections?.length||0} collections</small></div><strong>${money(outstanding(s))}</strong>${btn('Collect / history','collect',`data-id="${s.id}"`)}</div>`).join('')||'<p>No pending customer balances.</p>'}`);return}
 if(a==='collect'){const s=await db.sales.get(el.dataset.id);modal('Collect customer balance',`<form data-biz-form="collect" data-id="${s.id}"><h3>${esc(s.customer)} · ${money(outstanding(s))} due</h3><div class="mt-4">${field('Amount received (₹)','amount','','number',`required min="0.01" max="${outstanding(s)/100}" step="0.01"`)}</div><label class="mt-4">Payment method<select name="method"><option>Cash</option><option>Card</option><option>UPI</option></select></label><label class="mt-4"><input type="checkbox" required> I verified receipt of this payment.</label><div class="modal-actions"><button class="btn primary">Record payment</button></div></form><h3 class="mt-4">Payment history</h3>${(s.collections||[]).map(p=>`<div class="list-row">${esc(new Date(p.created).toLocaleString())}<span>${esc(p.method)} · ${money(p.amount)}</span></div>`).join('')||'<p class="help">No collections yet.</p>'}`);return}
 if(a==='returns'){modal('Returns & exchanges',`<p class="help mb-4">Choose the original bill. Refund selected items, then start a replacement sale for an exchange.</p>${(await db.sales.toArray()).filter(s=>s.status==='completed').reverse().map(s=>`<div class="list-row"><div>${esc(s.id)}<small>${esc(s.customer||'Walk-in')} · ${money(s.total)}</small></div>${btn('Return items','return',`data-id="${s.id}"`)}</div>`).join('')||'<p>No completed bills yet.</p>'}`);return}
 if(a==='return'){const s=await db.sales.get(el.dataset.id);modal('Return selected items',`<form data-biz-form="return" data-id="${s.id}"><p class="help">Refunds use original prices, allocated discounts and tax. Credit balances are reduced first. Record this only after arranging any cash/card/UPI refund.</p>${s.lines.map(l=>`<label class="mt-4">${esc(l.name)} · ${l.qty-returnedQty(s,l.id)} ${esc(l.unit)} available<input data-return-id="${l.id}" name="qty-${l.id}" type="number" min="0" max="${l.qty-returnedQty(s,l.id)}" step="${l.unit==='pcs'?1:.001}" value="0"></label>`).join('')}${field('Reason','reason','','text','required maxlength="200"')}<label class="mt-4">Refund method<select name="method"><option>Cash</option><option>Card</option><option>UPI</option></select></label><div id="return-quote" class="notice mt-4">Choose quantities to see the refund.</div><label class="mt-4"><input type="checkbox" name="exchange"> Start a replacement bill after this return</label><label><input type="checkbox" required> Returned items are resalable and any refund has been arranged.</label><div class="modal-actions"><button class="btn primary">Confirm return</button></div></form>`);const f=$('[data-biz-form=return]');f.oninput=()=>{try{const q=returnQuote(s,[...f.querySelectorAll('[data-return-id]')].map(x=>({id:x.dataset.returnId,qty:+x.value})));$('#return-quote').textContent=`Return value ${money(q.amount)} · reduce credit ${money(q.creditReduction)} · refund ${money(q.refund)}`}catch(e){$('#return-quote').textContent=e.message}};return}
 if(a==='suppliers'){const purchases=(await db.settings.toArray()).filter(r=>r.key.startsWith('purchase:')).map(r=>r.value).sort((a,b)=>b.created.localeCompare(a.created));modal('Supplier history & price watch',`<p class="help mb-4">Purchase subtotals before tax and charges. Record invoices through the purchase scanner.</p>${supplierComparisons(purchases).map(rows=>`<div class="notice mb-4"><strong>${esc(rows[0].name)} · supplier comparison</strong>${rows.map(r=>`<p class="help">${esc(r.supplier)}: ${money(r.cost)} / ${esc(r.unit)} · last purchased ${esc(r.date)}</p>`).join('')}<small>Lowest recorded latest supplier rate shown first; availability and terms may differ.</small></div>`).join('')}${purchases.map(p=>`<section class="panel mb-4"><h3>${esc(p.supplier)} · ${esc(p.invoice)}</h3><p class="help">${esc(day(p.created))} · purchase ${money(p.total)} · due ${money(p.total-p.paid-(p.payments||[]).reduce((n,x)=>n+x.amount,0))}</p>${p.rows.map(r=>`<div class="list-row"><span>${esc(r.name)} · ${r.stock} ${esc(r.unit)}</span><span>${money(Math.round(r.cost*100))}${r.previousCost?` <small>${Math.round((r.cost*100/r.previousCost-1)*100)}% vs prior cost</small>`:''}</span></div>`).join('')}${btn('Record supplier payment','supplier-pay',`data-id="${p.id}"`)}</section>`).join('')||'<p>No supplier invoices recorded yet.</p>'}`);return}
 if(a==='supplier-pay'){const row=(await db.settings.toArray()).find(r=>r.key.startsWith('purchase:')&&r.value.id===el.dataset.id);if(!row)throw Error('Purchase not found.');const p=row.value,due=p.total-p.paid-(p.payments||[]).reduce((n,x)=>n+x.amount,0);modal('Supplier payment',`<form data-biz-form="supplier-pay" data-key="${esc(row.key)}"><p>${esc(p.supplier)} · ${esc(p.invoice)} · due ${money(due)}</p>${field('Amount paid (₹)','amount','','number',`required min="0.01" max="${due/100}" step="0.01"`)}<label><input type="checkbox" required> Payment was made outside SpeedBill.</label><div class="modal-actions"><button class="btn primary">Record payment</button></div></form>`);return}
 if(a==='reorder'){const rows=reorderRows(await db.products.toArray(),await db.sales.toArray());modal('Smart reorder basket',`<p class="help mb-4">Last 30 days of sales × (supplier lead time + 7 safety days), with your minimum stock as the floor. Suggestions do not place orders.</p>${rows.map(p=>`<div class="list-row"><div><strong>${esc(p.name)}</strong><small>${p.perDay.toFixed(2)}/day · lead ${p.lead} days · stock ${p.stock} · minimum ${p.min}</small></div><strong>${p.orderQty} ${esc(p.unit)}</strong>${btn('Set limits','stock-rule',`data-id="${p.id}"`)}</div>`).join('')||'<p>No reorder suggestions.</p>'}${btn('Export purchase list','reorder-export')}${btn('Configure any product','stock-all')}`);return}
 if(a==='stock-all'){modal('Stock rules',`${(await db.products.toArray()).map(p=>`<div class="list-row">${esc(p.name)}${btn('Set limits','stock-rule',`data-id="${p.id}"`)}</div>`).join('')}`);return}
 if(a==='stock-rule'){const p=await db.products.get(el.dataset.id);modal('Reorder rule',`<form data-biz-form="stock-rule" data-id="${p.id}"><h3>${esc(p.name)}</h3>${field('Minimum stock','minStock',p.minStock??10,'number','min="0" step="0.001" required')}${field('Supplier lead time (days)','leadDays',p.leadDays??7,'number','min="1" max="365" step="1" required')}<div class="modal-actions"><button class="btn primary">Save rule</button></div></form>`);return}
 if(a==='reorder-export'){download('reorder-'+day()+'.json',JSON.stringify(reorderRows(await db.products.toArray(),await db.sales.toArray()),null,2));return}
 if(a==='identity'){const s=ctx.state.settings;modal('Business & tax details',`<form data-biz-form="identity">${field('Business tax ID / GSTIN','taxId',s.taxId||'')}${field('Customer tax ID for active bill','customerTaxId',ctx.state.customerTaxId||'')}${field('Invoice prefix (letters, numbers, hyphen)','invoicePrefix',s.invoicePrefix||'SB','text','required pattern="[A-Za-z0-9-]{1,12}"')}${field('Business phone','phone',s.phone||'')}${field('Business email','email',s.email||'','email')}<p class="help">New invoices use this prefix and an automatic sequential number. Tax rates remain configurable per inventory item.</p><div class="modal-actions"><button class="btn primary">Save details</button></div></form>`);return}
 if(a==='security'){modal('Cashier & manager access',`<div class="notice mb-4">Local PIN controls prevent routine cashier changes. This offline app is not tamper-proof against someone with browser or file access.</div><form data-biz-form="security">${field('Cashier name','cashier',ctx.state.settings.cashier,'text','required maxlength="60"')}${field('Set / replace manager PIN (6–12 digits)','pin','','password','pattern="[0-9]{6,12}" autocomplete="new-password"')}<p class="help">Leave PIN blank to keep the current PIN. Existing PIN approval is required to change cashier or security settings.</p><div class="modal-actions"><button class="btn primary">Save / switch cashier</button></div></form>`);return}
 if(a==='labels'){const p=await db.products.toArray();modal('Shelf price labels',`<p class="help mb-4">Select products. Labels include selling price, unit and SKU. Print using your browser.</p><form data-biz-form="labels">${p.map(x=>`<label class="list-row"><span><input type="checkbox" name="${x.id}"> ${esc(x.name)}</span><strong>${money(x.price)}</strong></label>`).join('')}<div class="modal-actions"><button class="btn primary">Print selected labels</button></div></form>`);return}
 if(a==='voice'){modal('Voice-assisted billing',`<p class="help">Say or type quantities and names, separated by “and” or commas. Example: “two milk, one bread”. Review matches before adding. Voice support depends on your browser; recognition may use its online speech service.</p><form data-biz-form="voice"><label class="mt-4">Items<textarea name="text" id="voice-text" required></textarea></label><div class="modal-actions">${btn('Start microphone','microphone')}<button class="btn primary">Review matches</button></div></form><div id="voice-review"></div>`);return}
 if(a==='microphone'){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)throw Error('Voice recognition unavailable here. Type the items instead.');const recognition=new Recognition();recognition.lang='en-IN';recognition.onresult=e=>{if($('#voice-text'))$('#voice-text').value=e.results[0][0].transcript};recognition.onerror=e=>ctx.toast('Voice recognition: '+e.error,true);recognition.start();return}
 if(a==='voice-add'){const f=$('#voice-matches');const rows=[...f.querySelectorAll('select')].map(x=>({id:x.value,qty:+x.dataset.voiceQty}));if(rows.some(r=>!r.id))throw Error('Select a product for each spoken item.');await ctx.addReviewed(rows);return}
 if(a==='display'){window.open('./customer.html','speedbill-customer');ctx.publish();modal('Customer-facing display',`<p class="help">Move the new display window to your second monitor. It updates with the active bill and shows the receipt QR after payment. Both windows must use this same browser profile and address.</p>`);return}
 if(a==='network'){const r=await fetch('/api/receipt-status',{cache:'no-store'});if(!r.ok)throw Error('Restart A1 TRADERS to load receipt connection checks.');const s=await r.json();modal('Receipt QR connection',`<div class="notice">${s.hosted?'Hosted receipts configured':'Local Wi-Fi receipts'}</div><p class="help mt-4">${s.hosted?'QR links use your configured public HTTPS receipt service.':'Your phone must be on the same Wi-Fi. Turn off mobile data/VPN for this test and open one of the addresses below on your phone.'}</p>${s.addresses.map(a=>`<p class="mt-4"><a href="${esc(a)}" target="_blank" rel="noopener">${esc(a)}</a></p>`).join('')}<p class="help mt-4">If the health page does not open on the phone, the firewall or router is blocking the connection. If Windows prompts, allow Node.js on your trusted private network. Public links require deploying the included hosted-receipts folder.</p>`);return}
}
async function submit(type,data,form){
 if(type==='collect'){await collectCredit(form.dataset.id,Math.round(+data.amount*100),data.method,ctx.state.settings.cashier);ctx.closeModal();await ctx.refresh();ctx.toast('Customer payment recorded.');return}
 if(type==='return'){if(!await managerApproval('Approve this return and refund record'))return;const selected=[...form.querySelectorAll('[data-return-id]')].map(x=>({id:x.dataset.returnId,qty:+x.value}));await recordReturn(form.dataset.id,selected,data.reason,data.method,ctx.state.settings.cashier);ctx.closeModal();await ctx.refresh();if(data.exchange)await ctx.startExchange(form.dataset.id);ctx.toast('Return recorded and stock restored.');return}
 if(type==='stock-rule'){await db.products.update(form.dataset.id,{minStock:+data.minStock,leadDays:+data.leadDays});ctx.closeModal();await ctx.refresh();ctx.toast('Reorder rule saved.');return}
 if(type==='supplier-pay'){await db.transaction('rw',db.settings,db.audit,async()=>{const row=await db.settings.get(form.dataset.key),p=row.value,amount=Math.round(+data.amount*100),due=p.total-p.paid-(p.payments||[]).reduce((n,x)=>n+x.amount,0);if(!Number.isSafeInteger(amount)||amount<=0||amount>due)throw Error('Invalid supplier payment.');p.payments=[...(p.payments||[]),{amount,created:new Date().toISOString()}];await db.settings.put(row);await audit('Supplier payment',`${p.supplier} · ${p.invoice} · ${amount} paise`,ctx.state.settings.cashier)});ctx.closeModal();ctx.toast('Supplier payment recorded.');return}
 if(type==='identity'||type==='security'){if(!await managerApproval('Approve business settings / cashier change'))return;if(type==='security'&&data.pin){const salt=uid(),hash=await pinDigest(data.pin,salt);await db.settings.put({key:'manager-lock',value:{salt,hash}})}const clean={...data};delete clean.pin;if(type==='identity'){ctx.state.customerTaxId=data.customerTaxId;delete clean.customerTaxId}ctx.state.settings={...ctx.state.settings,...clean};await db.transaction('rw',db.settings,db.audit,async()=>{await db.settings.put({key:'preferences',value:ctx.state.settings});await audit(type==='security'?'Cashier / PIN changed':'Business details updated',type==='security'?data.cashier:data.invoicePrefix,ctx.state.settings.cashier)});ctx.closeModal();ctx.shell();ctx.toast('Settings saved.');return}
 if(type==='labels'){const rows=(await db.products.toArray()).filter(p=>data[p.id]);if(!rows.length)throw Error('Select products first.');$('#print-area').innerHTML=`<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8mm">${rows.map(p=>`<section style="border:1px dashed #555;padding:6mm;break-inside:avoid"><img src="assets/logo-mono.svg" style="width:30mm"><h3>${esc(p.name)}</h3><h2>${money(p.price)}</h2><p>Per ${esc(p.unit)} · before tax ${p.tax}%</p><small>${esc(p.sku)}</small></section>`).join('')}</div>`;let style=$('#print-page-style');if(!style){style=document.createElement('style');style.id='print-page-style';document.head.append(style)}style.textContent='@media print{@page{size:A4;margin:10mm}#print-area{width:100%!important}}';window.print();return}
 if(type==='voice'){const rows=parseVoice(data.text,await db.products.toArray());if(!rows.length)throw Error('Enter some product names.');$('#voice-review').innerHTML=`<div id="voice-matches" class="mt-4">${rows.map(r=>`<label>${r.qty} × ${esc(r.query)}<select data-voice-qty="${r.qty}"><option value="">Choose product</option>${ctx.state.products.map(p=>`<option value="${p.id}" ${r.matches.length===1&&r.matches[0].id===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label>`).join('')}${btn('Add reviewed items','voice-add')}</div>`;return}
}
