import {db,uid,audit,totals} from './core.js';
export const day=d=>new Date(d||Date.now()).toLocaleDateString('en-CA');
export const sum=(rows,key)=>rows.reduce((n,r)=>n+(r[key]||0),0);
export const returnedQty=(s,id)=>sum((s.returns||[]).flatMap(r=>r.lines).filter(l=>l.id===id),'qty');
export const outstanding=s=>Math.max(0,(s.payments||[]).filter(p=>p.method==='Credit').reduce((n,p)=>n+p.amount,0)-sum(s.collections||[],'amount')-sum(s.returns||[],'creditReduction'));
export function returnQuote(s,selected){
 if(s.status!=='completed')throw Error('Only completed sales can be returned.');
 const seen=new Set();const lines=selected.filter(r=>Number(r.qty)>0).map(r=>{const l=s.lines.find(l=>l.id===r.id);const qty=Number(r.qty),prior=returnedQty(s,r.id);if(!l||seen.has(r.id)||!Number.isFinite(qty)||qty<=0||Math.round((prior+qty)*1000)>Math.round(l.qty*1000)||(l.unit==='pcs'&&!Number.isInteger(qty)))throw Error('Return quantity exceeds remaining sold quantity.');seen.add(r.id);
 const allocation=k=>Math.round(l[k]*(prior+qty)/l.qty)-Math.round(l[k]*prior/l.qty);return {id:l.id,name:l.name,qty,unit:l.unit,amount:allocation('total'),taxable:allocation('taxable'),cost:Math.round((l.cost||0)*(prior+qty))-Math.round((l.cost||0)*prior)};});
 if(!lines.length)throw Error('Enter at least one return quantity.');const amount=sum(lines,'amount'),creditReduction=Math.min(outstanding(s),amount);return {lines,amount,creditReduction,refund:amount-creditReduction};
}
export async function recordReturn(id,selected,reason,method,actor){if(!reason.trim()||!['Cash','Card','UPI'].includes(method))throw Error('Enter a reason and refund method.');return db.transaction('rw',db.sales,db.products,db.audit,async()=>{const s=await db.sales.get(id);if(!s)throw Error('Sale not found.');const quote=returnQuote(s,selected);for(const l of quote.lines){const p=await db.products.get(l.id);if(!p)throw Error('Inventory record is missing.');await db.products.update(p.id,{stock:Math.round((p.stock+l.qty)*1000)/1000})}const record={id:uid(),created:new Date().toISOString(),...quote,reason,method,actor};await db.sales.update(id,{returns:[...(s.returns||[]),record]});await audit('Partial return',`${id} · refund ${quote.refund} paise · credit reduced ${quote.creditReduction} paise · ${reason}`,actor);return record})}
export async function collectCredit(id,amount,method,actor){return db.transaction('rw',db.sales,db.audit,async()=>{const s=await db.sales.get(id);if(!s||s.status!=='completed'||!Number.isSafeInteger(amount)||amount<=0||amount>outstanding(s)||!['Cash','Card','UPI'].includes(method))throw Error('Payment must be positive and no greater than the outstanding balance.');const entry={id:uid(),created:new Date().toISOString(),amount,method};await db.sales.update(id,{collections:[...(s.collections||[]),entry]});await audit('Credit payment collected',`${id} · ${amount} paise · ${method}`,actor)})}
export function profitReport(sales,date){const sold=sales.filter(s=>s.status==='completed'&&day(s.created)===date),returns=sales.flatMap(s=>s.returns||[]).filter(r=>day(r.created)===date);const revenue=sold.reduce((n,s)=>n+s.lines.reduce((a,l)=>a+l.taxable,0),0)-returns.reduce((n,r)=>n+sum(r.lines,'taxable'),0);const cost=sold.reduce((n,s)=>n+s.lines.reduce((a,l)=>a+Math.round((l.cost||0)*l.qty),0),0)-returns.reduce((n,r)=>n+sum(r.lines,'cost'),0);return {bills:sold.length,revenue,cost,profit:revenue-cost,discounts:sold.reduce((n,s)=>n+s.lineDiscount+s.invoiceDiscount,0),returns:sum(returns,'amount')};}
export function reorderRows(products,sales,days=30){const cutoff=Date.now()-days*86400000;return products.map(p=>{let sold=0;for(const s of sales)if(s.status==='completed'&&Date.parse(s.created)>=cutoff)for(const l of s.lines)if(l.id===p.id)sold+=Math.max(0,l.qty-returnedQty(s,l.id));const perDay=sold/days,lead=Number(p.leadDays)||7,min=Number(p.minStock??10),target=Math.max(min,perDay*(lead+7));const qty=Math.max(0,Math.ceil((target-p.stock)*(p.unit==='pcs'?1:1000))/(p.unit==='pcs'?1:1000));return {...p,perDay,lead,min,target,orderQty:qty}}).filter(p=>p.orderQty>0)}
export function guardLines(cart,discount){return totals(cart,discount).lines.filter(l=>l.taxable<Math.round((l.cost||0)*l.qty)).map(l=>({...l,loss:Math.round(l.cost*l.qty)-l.taxable,floor:discount>=100||l.discount>=100?null:Math.ceil(l.cost/((1-l.discount/100)*(1-discount/100)))}))}
export async function fingerprint(data){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',typeof data==='string'?new TextEncoder().encode(data):data)),x=>x.toString(16).padStart(2,'0')).join('')}
export async function purchaseRecord(rows,meta,products){
 const supplier=String(meta.supplier||'').trim(),invoice=String(meta.invoice||'').trim();if(!supplier||!invoice)throw Error('Enter supplier name and invoice number before saving stock.');
 const key='purchase:'+await fingerprint(supplier.toLowerCase()+'|'+invoice.toLowerCase());const total=meta.receiving?meta.receiving.reduce((n,r)=>n+r.billedTotal,0):rows.reduce((n,r)=>n+Math.round(r.cost*100*r.stock),0),paid=Math.round(Number(meta.paid||0)*100);if(!Number.isSafeInteger(paid)||paid<0||paid>total)throw Error('Supplier payment must be between zero and the purchase subtotal.');
 return {key,value:{id:uid(),supplier,invoice,created:new Date().toISOString(),hash:meta.hash||'',total,paid,payments:[],rows:rows.map(r=>({...r,previousCost:products.find(p=>p.name.toLowerCase()===r.name.toLowerCase()&&p.unit===r.unit)?.cost??null}))}};
}
export function invoiceIssues(rows,products,declared){const issues=[],names=new Set();for(const [i,r]of rows.entries()){const name=String(r.name).trim().toLowerCase()+'|'+r.unit;if(names.has(name))issues.push(`Row ${i+1}: duplicate item; combine quantities.`);names.add(name);if(!Number.isFinite(+r.cost)||+r.cost<=0)issues.push(`Row ${i+1}: supplier rate needs review.`);if(+r.stock<=0)issues.push(`Row ${i+1}: quantity must be positive.`);if(r.lineTotal!==undefined&&r.lineTotal!==''&&Math.abs(Math.round(+r.lineTotal*100)-Math.round(+r.cost*+r.stock*100))>1)issues.push(`Row ${i+1}: supplier line total does not match quantity × rate.`);const old=products.find(p=>p.name.toLowerCase()===String(r.name).trim().toLowerCase()&&p.unit===r.unit);if(old?.cost&&Math.round(+r.cost*100)!==old.cost)issues.push(`${r.name}: cost ${Math.round((+r.cost*100/old.cost-1)*100)}% vs current inventory cost.`)}const subtotal=rows.reduce((n,r)=>n+Math.round((+r.cost||0)*(+r.stock||0)*100),0);if(declared!==''&&declared!==undefined&&Math.abs(Math.round(+declared*100)-subtotal)>1)issues.push('Declared supplier subtotal differs from the reviewed lines (compare before tax/charges).');return issues}
export function parseVoice(text,products){const numbers={one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10};return text.toLowerCase().split(/,|\band\b|\n/).map(part=>{const m=part.trim().match(/^(\d+(?:\.\d+)?|one|two|three|four|five|six|seven|eight|nine|ten)\s+(.+)$/);const qty=m?(numbers[m[1]]||Number(m[1])):1,query=(m?m[2]:part).trim();const matches=products.filter(p=>p.name.toLowerCase().includes(query));return {query,qty,matches}}).filter(r=>r.query)}
export function supplierComparisons(purchases){const latest=new Map();for(const p of [...purchases].sort((a,b)=>b.created.localeCompare(a.created)))for(const r of p.rows){const key=r.name.toLowerCase()+'|'+r.unit+'|'+p.supplier.toLowerCase();if(!latest.has(key))latest.set(key,{name:r.name,unit:r.unit,cost:Math.round(r.cost*100),supplier:p.supplier,date:day(p.created)})}const products=new Map();for(const row of latest.values()){const key=row.name.toLowerCase()+'|'+row.unit;if(!products.has(key))products.set(key,[]);products.get(key).push(row)}return [...products.values()].filter(rows=>rows.length>1).map(rows=>rows.sort((a,b)=>a.cost-b.cost))}
