import {db,uid,audit,esc,money,commitSale} from './core.js';
import {managerApproval} from './business.js';
import {validateBackup} from './operations.js';
import {pdfLogo} from './brand.js';
const $=s=>document.querySelector(s),b=(label,action,attrs='')=>`<button type="button" class="btn" data-control="${action}" ${attrs}>${label}</button>`;
let ctx;
export function convertDelivery({packs,perPack,packCost,received,damaged,unit='pcs'}){
 const a=[packs,perPack,packCost,received,damaged].map(Number);if(a.some(n=>!Number.isFinite(n)||n<0)||+packs<=0||+perPack<=0)throw Error('Enter valid pack, rate and delivery quantities.');
 const billed=+packs*+perPack;if(unit==='pcs'&&[billed,+received,+damaged].some(n=>!Number.isInteger(n)))throw Error('Piece quantities must be whole numbers.');
 if(+received>billed||+damaged>+received)throw Error('Received cannot exceed billed; damaged cannot exceed received.');
 const accepted=Math.round((+received-+damaged)*1000)/1000,missing=Math.round((billed-+received)*1000)/1000,cost=+packCost/+perPack;
 return {billed,received:+received,damaged:+damaged,accepted,missing,cost:Math.round(cost*100)/100,claim:Math.round((missing+(+damaged))*cost*100),billedTotal:Math.round(+packs*+packCost*100)};
}
export function stockHistory(rows){let prior=new Map(),result=[];for(const r of rows){if(!r.stockSnapshot){for(const d of r.stockChanges||[])result.push({...d,time:r.time,event:r.event,actor:r.actor,details:r.details});continue;}const current=new Map(r.stockSnapshot.map(p=>[p.id,p]));for(const p of current.values()){const old=prior.get(p.id);if(!old||old.stock!==p.stock)result.push({time:r.time,event:prior.size?r.event:'Opening snapshot',name:p.name,id:p.id,unit:p.unit,before:old?.stock??0,after:p.stock,change:Math.round((p.stock-(old?.stock??0))*1000)/1000,actor:r.actor,details:r.details})}for(const p of prior.values())if(!current.has(p.id))result.push({time:r.time,event:r.event,name:p.name,id:p.id,unit:p.unit,before:p.stock,after:0,change:-p.stock,actor:r.actor});prior=current}return result.reverse()}
export function setupControl(context){ctx=context;let queue=Promise.resolve();document.addEventListener('click',e=>{const el=e.target.closest('[data-control]');if(!el)return;queue=queue.then(()=>action(el.dataset.control,el)).catch(e=>ctx.toast(e.message,true))});document.addEventListener('submit',e=>{if(!e.target.matches('[data-control-form]'))return;e.preventDefault();const form=e.target;queue=queue.then(()=>submit(form)).catch(e=>ctx.toast(e.message,true))});}
async function action(a,el){
 if(a==='hub')return ctx.modal('Receiving & control',`<p class="help mb-4">Check deliveries, trace stock changes and resolve interrupted work.</p><div class="business-grid">${[['receiving','Pack conversion & receiving'],['claims','Supplier claim PDFs'],['evidence','Invoice source evidence'],['stock','Stock movement history'],['adjust','Physical stock count'],['payments','Payment verification'],['recovery','Checkout recovery'],['cloud','Counter sync & backup'],['links','Receipt delivery']].map(([a,t])=>b(t,a)).join('')}</div>`);
 if(a==='receiving'){
 if(!ctx.state.scanRows.length)throw Error('Scan a supplier bill first, then open Packs & delivery.');if(ctx.state.scanImported)throw Error('This invoice is already saved. Start a new scan for another delivery.');if(ctx.state.receiving)throw Error('Pack conversion was applied to this review. Re-scan to change the original pack quantities.');
 ctx.modal('Packs & delivery',`<p class="help mb-4">Enter the supplier’s pack rate and the number of individual units delivered. Only received, undamaged units enter inventory. Selling rates stay per individual unit.</p><form data-control-form="receiving"><div class="table-wrap"><table><thead><tr><th>Item</th><th>Billed packs</th><th>Units / pack</th><th>₹ / pack</th><th>Units received</th><th>Damaged units</th></tr></thead><tbody>${ctx.state.scanRows.map((r,i)=>`<tr data-delivery="${i}"><td>${esc(r.name)}</td>${[['packs',r.stock],['perPack',1],['packCost',r.cost],['received',r.stock],['damaged',0]].map(([f,v])=>`<td><input aria-label="${f} for ${esc(r.name)}" name="${f}-${i}" type="number" min="0" step="0.001" value="${esc(v)}" required></td>`).join('')}</tr>`).join('')}</tbody></table></div><div id="delivery-summary" class="notice mt-4"></div><div class="modal-actions"><button class="btn primary">Apply reviewed delivery</button></div></form>`);const form=$('[data-control-form=receiving]');form.oninput=()=>{try{$('#delivery-summary').textContent=readDelivery(form).map(r=>`${r.name}: accept ${r.accepted}, missing ${r.missing}, damaged ${r.damaged}, claim ${money(r.claim)}`).join(' • ')}catch(e){$('#delivery-summary').textContent=e.message}};form.oninput();return;
 }
 if(a==='evidence'){
 const source=ctx.state.scanImage;if(!source||ctx.state.scanSource==='demo')throw Error('Upload a real invoice to compare its source. Samples have no source evidence.');
 ctx.modal('Invoice source evidence',`<p class="help">Select an item to inspect its values beside the original bill. Highlighting is manual; OCR bounding boxes are not available.</p><div class="evidence-grid"><div>${ctx.state.scanRows.map((r,i)=>b(r.name,'evidence-row',`data-index="${i}"`)).join('')}<div id="evidence-detail" class="notice mt-4">Choose an item.</div></div><div>${source.type==='application/pdf'?`<object type="application/pdf" data="${esc(source.dataURL)}" style="width:100%;height:65vh"><p>PDF preview unavailable. Open the original PDF to compare.</p></object>`:`<img src="${esc(source.dataURL)}" alt="Original supplier invoice" style="width:100%;height:auto">`}</div></div>`);return;
 }
 if(a==='evidence-row'){const r=ctx.state.scanRows[+el.dataset.index];$('#evidence-detail').innerHTML=`<strong>${esc(r.name)}</strong><p>Supplier rate: ${money(Math.round(r.cost*100))}</p><p>Quantity: ${esc(r.stock)} ${esc(r.unit)}</p><p>Your rate: ${r.price===''?'Not entered':money(Math.round(r.price*100))}</p><small>Close this view to correct the review table.</small>`;return}
 if(a==='claims'){const saved=(await db.settings.toArray()).filter(r=>r.key.startsWith('purchase:')&&r.value.receiving).map(r=>r.value);const current=ctx.state.receiving?{id:'current',supplier:ctx.state.purchaseMeta?.supplier||'Supplier',invoice:ctx.state.purchaseMeta?.invoice||'Current review',receiving:ctx.state.receiving}:null;ctx.claims=[...(current?[current]:[]),...saved];ctx.modal('Supplier claim PDFs',`${ctx.claims.map((p,i)=>`<div class="list-row"><div><strong>${esc(p.supplier)} · ${esc(p.invoice)}</strong><small>Claim ${money(p.receiving.reduce((n,r)=>n+r.claim,0))} · missing / damaged goods</small></div>${b('Download claim PDF','claim-pdf',`data-index="${i}"`)}</div>`).join('')||'<p>Review a delivery to prepare a claim.</p>'}<p class="help mt-4">Claims are review documents. They do not automatically reduce the supplier balance or send a message.</p>`);return}
 if(a==='claim-pdf'){await claimPDF(ctx.claims[+el.dataset.index]);return}
 if(a==='stock'){const rows=stockHistory(await db.audit.toArray());ctx.modal('Stock movement history',`<p class="help mb-4">Opening snapshot starts with this upgrade. Earlier stock changes cannot be reconstructed reliably.</p><input id="movement-search" placeholder="Search product, event or reference" aria-label="Search stock movements"><div id="movement-list"></div>`);const render=()=>{const q=$('#movement-search').value.toLowerCase();$('#movement-list').innerHTML=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q)).slice(0,200).map(r=>`<div class="list-row"><div><strong>${esc(r.name)}</strong><small>${esc(r.event)} · ${esc(new Date(r.time).toLocaleString())} · ${esc(r.actor)}</small><small>${esc(r.details||'')}</small></div><strong>${r.change>0?'+':''}${r.change} ${esc(r.unit)}<small>${r.before} → ${r.after}</small></strong></div>`).join('')||'<p>No stock movements yet.</p>'};$('#movement-search').oninput=render;render();return}
 if(a==='adjust'){ctx.modal('Physical stock count',`<form data-control-form="adjust"><label>Product<select name="id">${ctx.state.products.map(p=>`<option value="${p.id}">${esc(p.name)} · ${p.stock} ${esc(p.unit)}</option>`).join('')}</select></label><label>Actual counted stock<input name="stock" type="number" min="0" step="0.001" required></label><label>Reason<select name="reason"><option>Physical count correction</option><option>Damaged stock</option><option>Missing stock</option></select></label><label>Notes<input name="notes" maxlength="200" required></label><div class="modal-actions"><button class="btn primary">Save count & audit</button></div></form>`);return}
 if(a==='payments'){const sales=(await db.sales.toArray()).filter(s=>s.status==='completed'&&s.payments.some(p=>['Card','UPI'].includes(p.method)&&p.amount>0));ctx.modal('Payment verification',`<div class="notice amber mb-4">Manual verification mode. Check your bank or merchant app before confirming. A1 TRADERS does not query a payment provider.</div>${sales.reverse().map(s=>`<div class="list-row"><div><strong>${esc(s.id)} · ${money(s.total)}</strong><small>${esc(s.paymentVerification||'unverified')}${s.paymentReference?' · '+esc(s.paymentReference):''}</small></div>${b('Review','payment',`data-id="${s.id}"`)}</div>`).join('')||'<p>No digital payments recorded yet.</p>'}`);return}
 if(a==='payment'){ctx.modal('Review payment',`<form data-control-form="payment" data-id="${el.dataset.id}"><label>Status<select name="status"><option value="manually-confirmed">Manually confirmed</option><option value="pending">Pending</option><option value="failed">Failed</option><option value="refund-recorded">Refund recorded externally</option></select></label><label>Transaction reference / explanation<input name="reference" required maxlength="150"></label><label><input type="checkbox" required> I checked the bank / merchant payment record.</label><p class="help">Changing verification status does not cancel the sale, restore stock or transfer money. Use Returns for accounting adjustments.</p><div class="modal-actions"><button class="btn primary">Save verification</button></div></form>`);return}
 if(a==='recovery'){const intent=await db.drafts.get('checkout-intent'),done=intent?await db.settings.get('checkout:'+intent.checkoutId):null;ctx.modal('Checkout recovery',intent?`<p>${done?'This checkout already completed. Open its receipt; do not collect payment again.':'An interrupted checkout was found. Check payment receipt before completing the saved transaction.'}</p><p class="help">${esc(intent.created)} · ${intent.cart.length} items</p>${done?b('Open completed receipt','recover-open'):b('Complete saved checkout once','recover')}`:'<p>No interrupted checkout. Your active bill is saved automatically.</p>');return}
 if(a==='recover'||a==='recover-open'){const intent=await db.drafts.get('checkout-intent');if(!intent)throw Error('No recovery entry.');if(!await managerApproval('Recover interrupted checkout'))return;const sale=await commitSale(intent.cart,intent.discount,intent.payments,intent.customer,{...intent.settings,checkoutId:intent.checkoutId});await db.drafts.delete('checkout-intent');ctx.state.cart=[];ctx.state.discount=0;ctx.state.customer='';await ctx.refresh();await ctx.receiptModal(sale);return}
 if(a==='cloud'){await cloudDialog();return}
 if(a==='cloud-push'){await cloudPush();await cloudDialog();return}
 if(a==='cloud-pull'){if(ctx.state.cart.length)throw Error('Hold or finish the active bill before loading cloud data.');if(!await managerApproval('Load cloud store snapshot'))return;await cloudPull();location.reload();return}
 if(a==='links'){const rows=(await db.settings.toArray()).filter(r=>r.key.startsWith('receipt-link:'));ctx.modal('Receipt delivery',`<p class="help mb-4">Links expire. Reopen a bill to generate a fresh PDF link. Download counts mean file requests, not confirmed customer reading.</p>${rows.map(r=>`<div class="list-row"><div><strong>${esc(r.value.id)}</strong><small>Created ${esc(new Date(r.value.created).toLocaleString())} · ${r.value.minutes} minutes validity</small></div><a class="btn" href="${esc(r.value.url)}" target="_blank" rel="noopener">Open</a>${b('Delivery status','link-status',`data-key="${esc(r.key)}"`)}${b('Regenerate','regenerate',`data-id="${esc(r.value.id)}"`)}</div>`).join('')||'<p>No receipt links created.</p>'}`);return}
 if(a==='regenerate'){const s=await db.sales.get(el.dataset.id);if(!s)throw Error('Sale missing.');await ctx.receiptModal(s);return}
 if(a==='link-status'){const r=(await db.settings.get(el.dataset.key)).value;if(!r.token)throw Error('Download tracking is available for hosted receipts created in this version.');const data=await api('/api/receipt-status?token='+encodeURIComponent(r.token));ctx.toast(`${data.downloads} PDF requests · ${data.expired?'expired':'active'}`);return}
}
function readDelivery(form){const f=Object.fromEntries(new FormData(form));return ctx.state.scanRows.map((r,i)=>({...r,...convertDelivery(Object.fromEntries(['packs','perPack','packCost','received','damaged'].map(k=>[k,f[k+'-'+i]]).concat([['unit',r.unit]]))),packs:+f['packs-'+i],perPack:+f['perPack-'+i],packCost:+f['packCost-'+i]}))}
async function submit(form){if(!form.reportValidity())return;const f=Object.fromEntries(new FormData(form)),a=form.dataset.controlForm;
 if(a==='receiving'){const rows=readDelivery(form);ctx.state.receiving=rows;ctx.state.scanRows=rows.map(r=>({...r,stock:r.accepted,lineTotal:'',cost:r.cost}));ctx.closeModal();ctx.renderExtraction();ctx.toast('Pack conversion applied. Review unit selling rates before saving.');return}
 if(!await managerApproval('Approve '+a))return;
 if(a==='adjust'){await db.transaction('rw',db.products,db.audit,async()=>{const p=await db.products.get(f.id),stock=Number(f.stock);if(!p||!Number.isFinite(stock)||stock<0||(p.unit==='pcs'&&!Number.isInteger(stock)))throw Error('Invalid counted quantity.');await db.products.update(p.id,{stock});await audit(f.reason,`${p.name}: ${p.stock} → ${stock}. ${f.notes}`,ctx.state.settings.cashier)});await ctx.refresh()}
 if(a==='payment'){await db.transaction('rw',db.sales,db.audit,async()=>{await db.sales.update(form.dataset.id,{paymentVerification:f.status,paymentReference:f.reference});await audit('Payment verification',`${form.dataset.id} · ${f.status} · ${f.reference}`,ctx.state.settings.cashier)})}
 ctx.closeModal();ctx.toast('Saved with audit history.');
}
async function claimPDF(p){const {jsPDF,autoTable}=window.PDFEngine,doc=new jsPDF();const logo=await pdfLogo();doc.addImage(logo,'PNG',15,12,57,16);doc.setFontSize(18);doc.text('Supplier delivery claim',15,42);doc.setFontSize(10);doc.text(`${p.supplier} / ${p.invoice}`,15,51);autoTable(doc,{startY:59,head:[['Item','Billed','Received','Damaged','Missing','Claim INR']],body:p.receiving.map(r=>[r.name,r.billed,r.received,r.damaged,r.missing,(r.claim/100).toFixed(2)]),headStyles:{fillColor:[104,84,232]},styles:{fontSize:9}});const y=doc.lastAutoTable.finalY+12;if(y>265)doc.addPage();doc.text('Total claim INR '+(p.receiving.reduce((n,r)=>n+r.claim,0)/100).toFixed(2),15,y>265?20:y);doc.save('supplier-claim-'+String(p.invoice).replace(/[^a-z0-9-]/gi,'-')+'.pdf')}
async function api(path,options={}){const r=await fetch(path,options);if(!r.ok)throw Error(r.status===409?'Another counter changed the cloud snapshot. Load and reconcile before uploading again.':r.status===404?'Cloud service is unavailable on this local server. Open the deployed app.':await r.text());return r.json()}
const tables=['products','sales','parked','audit','settings'];
async function snapshot(){return Object.fromEntries(await Promise.all(tables.map(async t=>[t,(await db[t].toArray()).filter(r=>t!=='settings'||!r.key.startsWith('cloud-'))])))}
async function cloudDialog(){if(location.hostname.endsWith('.github.io')){ctx.modal('Local workspace','<p>Cloud snapshots require a separate backend. Use Settings → Download full backup to keep a copy of this device’s data.</p>');return;}let status;try{status=await api('/api/cloud')}catch(e){status={error:e.message}}ctx.modal('Counter sync & backup',`<div class="notice ${status.error?'amber':''}">${esc(status.error||`Cloud revision ${status.revision||0}. Store snapshots are private to your signed-in account.`)}</div><p class="help mt-4">Use the same signed-in account on each counter. Load before trading, upload after trading. Conflicting revisions are rejected and need reconciliation. Offline sales remain local until uploaded. This does not reserve stock across counters in real time.</p><p class="help">Loading keeps a local recovery copy and replaces inventory, sales and settings with the cloud snapshot. Local PIN rules can change with the snapshot.</p><div class="modal-actions">${b('Upload this counter','cloud-push',status.error?'disabled':'')}${b('Load cloud snapshot','cloud-pull',status.error?'disabled':'')}</div>`)}
async function cloudPush(){const base=(await db.settings.get('cloud-revision'))?.value||0;const data=await api('/api/cloud',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({base,data:await snapshot()})});await db.settings.put({key:'cloud-revision',value:data.revision});ctx.toast('Cloud snapshot saved.');}
async function cloudPull(){const remote=await api('/api/cloud?data=1');if(!remote.data)throw Error('No cloud snapshot yet.');await validateBackup({...remote.data,version:1,drafts:[]});await db.drafts.put({id:'before-cloud-load',cart:[],discount:0,customer:'',data:await snapshot(),created:new Date().toISOString()});await db.transaction('rw',tables.map(t=>db[t]),async()=>{for(const t of tables){await db[t].clear();await db[t].bulkPut(remote.data[t])}await db.settings.put({key:'cloud-revision',value:remote.revision})});}
