import * as THREE from '../vendor/three.module.js';
import {db} from './core.js';
const host=document.querySelector('#scene'),journey=document.querySelector('.journey'),stage=document.querySelector('.stage'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
const chapters=[['01 / DISCOVER','Every product.<br>In its place.','A clear catalog. The right price. Your next sale starts with one simple scan.','Your shelf, ready to sell'],['02 / SCAN','A small scan.<br>A smoother day.','Bring an item to the counter. Find it by barcode, name or SKU and keep the queue moving.','Item found · added to bill'],['03 / CALCULATE','Every detail.<br>Accounted for.','Quantities, discounts and tax come together in a clear bill. Review it before recording payment.','A clear total, before payment'],['04 / COMPLETE','A good sale.<br>A great finish.','Print a receipt or download a branded PDF. Then make room for the next customer.','Receipt ready · see you again']];
let current=-1,progress=0,manual=null,paused=reduced.matches,frame=0,renderer,scene,camera,world,product,beam,paper,screenTexture,screenCanvas,store='A1 TRADERS',targetX=0,targetY=0,active=true;
const clamp=(v)=>Math.max(0,Math.min(1,v));
function chapter(index){if(index===current)return;current=index;const c=chapters[index];document.querySelector('#chapter-kicker').textContent=c[0];document.querySelector('#chapter-title').innerHTML=c[1];document.querySelector('#chapter-description').textContent=c[2];document.querySelector('#scene-status').textContent=c[3];document.querySelectorAll('[data-stage]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));if(screenTexture)drawScreen(index);}
function drawScreen(index){const c=screenCanvas.getContext('2d');c.fillStyle='#102c25';c.fillRect(0,0,768,500);c.fillStyle='#c7ef7d';c.font='bold 28px Arial';c.fillText(store.slice(0,25),35,52);c.fillStyle='#89a597';c.font='15px Arial';c.fillText('REGISTER 01 / DEMO',35,80);for(let i=0;i<6;i++){c.fillStyle=['#345346','#476249','#658159'][i%3];c.fillRect(35+i%3*130,115+Math.floor(i/3)*128,112,107);c.fillStyle='#dce8cf';c.beginPath();c.arc(91+i%3*130,153+Math.floor(i/3)*128,22,0,Math.PI*2);c.fill();}c.fillStyle='#eff2df';c.font='22px Arial';c.fillText('Current bill',467,137);c.font='17px Arial';c.fillText(index>0?'Fresh milk       64.00':'Ready for your sale',467,188);if(index>1)c.fillText('Bread              55.00',467,225);c.fillStyle='#c7ef7d';c.fillRect(452,319,276,70);c.fillStyle='#173526';c.font='bold 25px Arial';c.fillText(index>2?'RECEIPT READY':index>1?'INR 119.00':'SCAN AN ITEM',474,363);c.fillStyle='#8ba695';c.font='14px Arial';c.fillText('Illustrative checkout',35,465);screenTexture.needsUpdate=true;}
function requestFrame(){if(!frame&&active&&!document.hidden)frame=requestAnimationFrame(render)}
function setup(){renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.setClearColor(0xe7e9dc,1);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.append(renderer.domElement);host.classList.add('webgl-ready');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(34,1,.1,60);scene.add(new THREE.HemisphereLight(0xffffff,0x607b55,1.8));const key=new THREE.DirectionalLight(0xfff6df,2);key.position.set(-3,9,7);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-7;key.shadow.camera.right=7;key.shadow.camera.top=7;key.shadow.camera.bottom=-7;key.shadow.normalBias=.03;scene.add(key);const fill=new THREE.DirectionalLight(0xc8eacb,1);fill.position.set(7,5,-5);scene.add(fill);world=new THREE.Group();scene.add(world);
const mat=(color,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness:.5,metalness});const ink=mat(0x18332c,.3),cream=mat(0xebe9d8),lime=mat(0xb8d87c),metal=mat(0x516b5c,.65);
function box(w,h,d,m,x,y,z,parent=world){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh}
const plinth=new THREE.Mesh(new THREE.CylinderGeometry(3.8,3.9,.27,80),cream);plinth.position.y=-.13;plinth.receiveShadow=true;world.add(plinth);box(1.6,.12,1.05,metal,-.65,.1,-.3);box(.22,1.25,.3,metal,-.65,.71,-.5);
const monitor=new THREE.Group();monitor.position.set(-.65,1.9,-.5);monitor.rotation.x=-.1;world.add(monitor);box(2.55,1.8,.17,ink,0,0,0,monitor);screenCanvas=document.createElement('canvas');screenCanvas.width=768;screenCanvas.height=500;screenTexture=new THREE.CanvasTexture(screenCanvas);screenTexture.colorSpace=THREE.SRGBColorSpace;const screen=new THREE.Mesh(new THREE.PlaneGeometry(2.36,1.54),new THREE.MeshBasicMaterial({map:screenTexture}));screen.position.z=.091;monitor.add(screen);drawScreen(0);
box(1.12,.62,1.12,ink,1.55,.36,.4);box(.95,.05,.7,metal,1.55,.69,.35);box(.8,.035,.075,mat(0x091811),1.55,.72,.35);const pc=document.createElement('canvas');pc.width=256;pc.height=512;const pctx=pc.getContext('2d');pctx.fillStyle='#fffdeb';pctx.fillRect(0,0,256,512);pctx.fillStyle='#203c2d';pctx.textAlign='center';pctx.font='bold 24px Arial';pctx.fillText('A1 TRADERS',128,45);pctx.font='14px Arial';pctx.fillText('THANK YOU',128,80);for(let i=0;i<6;i++)pctx.fillRect(28,120+i*35,i%2?150:200,4);for(let i=0;i<35;i++)pctx.fillRect(30+i*5,370,(i%3)+1,55);const pt=new THREE.CanvasTexture(pc);pt.colorSpace=THREE.SRGBColorSpace;paper=new THREE.Mesh(new THREE.PlaneGeometry(.74,1.48),new THREE.MeshStandardMaterial({map:pt,side:THREE.DoubleSide,roughness:.9}));paper.position.set(1.55,.78,.35);paper.rotation.x=-.2;world.add(paper);
box(.7,.09,.7,metal,-.4,.09,1.22);box(.55,.03,.54,mat(0x16261e),-.4,.155,1.22);beam=box(.55,.012,.018,new THREE.MeshBasicMaterial({color:0xc4ff78}),-.4,.18,1.22);
product=new THREE.Group();world.add(product);box(.55,.85,.5,cream,0,.45,0,product);box(.55,.22,.5,lime,0,.92,0,product);box(.35,.25,.012,lime,0,.48,.26,product);const cap=new THREE.Mesh(new THREE.CylinderGeometry(.085,.085,.07,20),ink);cap.position.set(.13,1.07,0);product.add(cap);
const apple=new THREE.Mesh(new THREE.SphereGeometry(.29,24,16),mat(0x87a548));apple.position.set(-1.8,.3,.9);apple.castShadow=true;world.add(apple);box(.055,.2,.055,ink,-1.8,.59,.9);box(.55,.12,.7,mat(0xb79760),-2.15,.1,-.25);box(.58,.12,.73,mat(0xd5bd82),-2.15,.23,-.25);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),mat(0xe7e9dc));floor.rotation.x=-Math.PI/2;floor.position.y=-.29;floor.receiveShadow=true;scene.add(floor);resize();chapter(0);requestFrame();}
function resize(){if(!renderer)return;const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();requestFrame()}
function render(time){frame=0;if(!renderer)return;const mobile=innerWidth<801;const scroll=clamp(-journey.getBoundingClientRect().top/Math.max(1,journey.offsetHeight-stage.offsetHeight));progress=manual??(paused?progress:scroll);chapter(Math.min(3,Math.floor(progress*3.99)));stage.style.setProperty('--progress',progress);world.rotation.y=-.2+progress*.65+(paused?0:targetX*.07);world.scale.setScalar(mobile?.74:1);world.position.set(mobile?0:1.8,mobile?-.35:0,0);camera.position.set(mobile?6:7,mobile?6.4:5.4,mobile?12.5:11);camera.lookAt(mobile?0:.2,mobile?1.1:.7,0);const move=clamp(progress*2.8);product.position.set(-2.4+move*3.2,.03+Math.sin(move*Math.PI)*.65,1.22);product.rotation.y=progress*1.5;beam.visible=current===1;beam.position.z=1.22+(paused?0:Math.sin(time*.005)*.22);const print=clamp((progress-.65)/.32);paper.scale.y=Math.max(.01,print);paper.position.y=.75+print*.72;paper.visible=print>.02;renderer.render(scene,camera);if(!paused&&active&&!document.hidden&&current===1)requestFrame();}
addEventListener('scroll',requestFrame,{passive:true});function resumeScroll(){if(!paused)manual=null;requestFrame()}addEventListener('wheel',resumeScroll,{passive:true});addEventListener('touchmove',resumeScroll,{passive:true});addEventListener('keydown',e=>{if(['PageDown','PageUp','ArrowDown','ArrowUp','Home','End'].includes(e.key))resumeScroll()});addEventListener('resize',resize);host.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;targetX=(e.clientX/innerWidth-.5);requestFrame()});document.querySelectorAll('[data-stage]').forEach(b=>b.addEventListener('click',()=>{manual=Number(b.dataset.stage)/3;progress=manual;chapter(Number(b.dataset.stage));requestFrame()}));const toggle=document.querySelector('#motion-toggle');function toggleState(){toggle.textContent=paused?'Resume motion':'Pause motion';toggle.setAttribute('aria-pressed',String(paused));requestFrame()}toggle.addEventListener('click',()=>{paused=!paused;toggleState()});reduced.addEventListener('change',()=>{paused=reduced.matches;toggleState()});new IntersectionObserver(([e])=>{active=e.isIntersecting;requestFrame()}).observe(journey);document.addEventListener('visibilitychange',requestFrame);try{setup()}catch(e){console.warn('3D preview unavailable; using photographic fallback.',e.message);document.querySelector('.scene-top>span').textContent='THE A1 EXPERIENCE';}toggleState();Dexie.liveQuery(()=>db.settings.get('preferences')).subscribe({next:row=>{store=row?.value?.store||'A1 TRADERS';document.querySelectorAll('[data-store-name]').forEach(el=>el.textContent=store);if(screenTexture){drawScreen(Math.max(0,current));requestFrame()}},error:()=>{}});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});



