import {db} from './core.js';
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const scene=document.querySelector('.scene'),terminal=document.querySelector('.hero-photo'),story=document.querySelector('.scroll-story');
let frame=0,pointerX=0,pointerY=0;
function animate(){frame=0;if(reduced.matches)return;const y=window.scrollY;scene.style.setProperty('--hero-shift',Math.min(55,y*.08)+'px');terminal.style.transform=`rotateY(${pointerX*4}deg) rotateX(${-pointerY*4}deg)`;const rect=story.getBoundingClientRect(),progress=Math.max(0,Math.min(1,-rect.top/(story.offsetHeight-innerHeight)));story.style.setProperty('--story-progress',progress);document.querySelectorAll('.story-card').forEach((card,i)=>{const phase=i===2?0:Math.max(0,Math.min(1,progress*2.4-i));card.style.transform=`translate3d(${(i-1)*20+phase*480}px,${-phase*65}px,${i*25}px) rotateY(${-phase*35}deg) rotateZ(${(i-1)*7-phase*14}deg)`;card.style.opacity=String(1-phase);card.style.zIndex=String(3-i)});}
function schedule(){if(!frame)frame=requestAnimationFrame(animate)}
scene.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const r=scene.getBoundingClientRect();pointerX=(e.clientX-r.left)/r.width-.5;pointerY=(e.clientY-r.top)/r.height-.5;schedule()});scene.addEventListener('pointerleave',()=>{pointerX=pointerY=0;schedule()});addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);reduced.addEventListener('change',()=>{if(reduced.matches){terminal.style.transform='';document.querySelectorAll('.story-card').forEach(c=>{c.style.opacity='';c.style.transform=''})}else schedule()});
if('IntersectionObserver'in window){document.body.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.feature-strip>div,.workflow>div,.workflow li').forEach(e=>{e.classList.add('reveal');observer.observe(e)})}schedule();
Dexie.liveQuery(()=>db.settings.get('preferences')).subscribe({next:row=>{const name=row?.value?.store||'A1 TRADERS';document.querySelectorAll('[data-store-name]').forEach(el=>el.textContent=name);document.title=name+' — Your retail workspace'},error:()=>{}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
