import {createWalkthrough} from './walkthrough.js';
import {db} from './core.js';
const journey=document.querySelector('.journey'),stage=document.querySelector('.stage'),picture=document.querySelector('#store-scene'),copy=document.querySelector('#chapter-copy'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
const chapters=[['CHAPTER 01 / OPEN THE DOORS','A good day<br>begins <em>here.</em>','For the shops that make a neighbourhood.<br>And the people who keep them moving.','STEP INSIDE','pos'],['CHAPTER 02 / THE SHELVES','Every shelf.<br><em>A possibility.</em>','Know what came in. Know what is ready.<br>Your products, quantities, and prices in view.','EXPLORE INVENTORY','inventory'],['CHAPTER 03 / THE COUNTER','Less waiting.<br><em>More living.</em>','A quick scan. A clear bill.<br>A checkout that keeps pace with your day.','OPEN THE COUNTER','pos'],['CHAPTER 04 / THE RECEIPT','A good sale.<br><em>A lasting impression.</em>','A branded receipt to print, download, or share.<br>A clear record of every finished sale.','VIEW SALES & RECEIPTS','sales'],['CHAPTER 05 / THE BIGGER PICTURE','Today, understood.<br><em>Tomorrow, considered.</em>','Look beyond your sales total.<br>See gross profit after the original cost of goods.','EXPLORE YOUR OVERVIEW','dashboard']];
let walkthrough;try{walkthrough=createWalkthrough(document.querySelector('.cinema'))}catch(error){console.info('Using illustrated fallback',error.message)};
let touring=false,tourTime=0,tourStart=0;
let current=0,progress=0,paused=reduced.matches,manual=null,frame=0,timer=0,visible=true,last=0,t=0;
const buttons=[...document.querySelectorAll('[data-chapter]')],toggle=document.querySelector('#motion-toggle'),canvas=document.querySelector('#dust'),ctx=canvas.getContext('2d');let w=0,h=0;
const motes=Array.from({length:24},(_,i)=>({x:((i*137)%997)/997,y:((i*79)%683)/683,r:.4+(i%3)*.3,s:.2+(i%5)*.12}));
function renderChapter(index,immediate=false){if(index===current&&!immediate)return;current=index;clearTimeout(timer);copy.classList.add('changing');const update=()=>{const c=chapters[index];stage.classList.toggle('right',index%2===1);document.querySelector('#chapter-kicker').textContent=c[0];document.querySelector('#chapter-title').innerHTML=c[1];document.querySelector('#chapter-description').innerHTML=c[2];const link=document.querySelector('#chapter-link');link.innerHTML=c[3]+' <span>↗</span>';link.href='index.html#'+c[4];document.querySelector('#chapter-number').textContent=String(index+1).padStart(2,'0');buttons.forEach((b,i)=>{if(i===index)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});copy.classList.remove('changing')};if(immediate||reduced.matches)update();else timer=setTimeout(update,190)}
function request(){if(!frame&&visible&&!document.hidden)frame=requestAnimationFrame(draw)}
function draw(now){frame=0;if(last&&now-last<32&&!paused){request();return}const dt=last?Math.min((now-last)/1000,.06):0;last=now;if(!paused)t+=dt;if(touring&&!paused){tourTime+=dt;progress=Math.min(1,tourTime/22);manual=progress;if(progress===1){touring=false;tourButton.textContent='PLAY WALKTHROUGH ▷';tourButton.setAttribute('aria-pressed','false');document.querySelector('.story-floor').classList.remove('tour-active')}}const p=manual??Math.max(0,Math.min(1,-journey.getBoundingClientRect().top/Math.max(1,journey.offsetHeight-stage.offsetHeight)));if(!paused)progress=p;renderChapter(Math.min(4,Math.floor(progress*4.999)));stage.style.setProperty('--progress',progress);walkthrough?.render(progress,paused||reduced.matches);if(!paused&&!reduced.matches)picture.style.transform=`scale(${1.02+progress*.24}) translate(${-progress*4}%,${progress*1.2}%)`;ctx.clearRect(0,0,w,h);if(!reduced.matches){motes.forEach(m=>{const x=(m.x*w+Math.sin(t*.12+m.y*8)*20),y=(m.y*h-t*m.s*5+h*10)%h;ctx.beginPath();ctx.fillStyle='rgba(248,213,151,.22)';ctx.arc(x,y,m.r,0,Math.PI*2);ctx.fill()})}if(!paused)request()}
function resize(){walkthrough?.resize();w=stage.clientWidth;h=stage.clientHeight;const d=Math.min(devicePixelRatio,1.5);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);request()}
function resumeScroll(){if(touring&&event?.type==='wheel'){touring=false;manual=null;document.querySelector('.story-floor').classList.remove('tour-active');tourButton.setAttribute('aria-pressed','false');tourButton.textContent='PLAY WALKTHROUGH ▷'}else if(!touring)manual=null;tourButton.textContent='PLAY WALKTHROUGH ▷';tourButton.setAttribute('aria-pressed','false');request()}
addEventListener('scroll',request,{passive:true});addEventListener('wheel',resumeScroll,{passive:true});addEventListener('touchmove',resumeScroll,{passive:true});addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp','PageDown','PageUp','Home','End'].includes(e.key))resumeScroll()});addEventListener('resize',resize);
buttons.forEach((b,i)=>b.addEventListener('click',()=>{touring=false;tourButton.textContent='PLAY WALKTHROUGH ▷';tourButton.setAttribute('aria-pressed','false');progress=i/4;manual=progress;renderChapter(i,true);if(!paused&&!reduced.matches){const top=journey.getBoundingClientRect().top+scrollY;scrollTo({top:top+(journey.offsetHeight-stage.offsetHeight)*progress,behavior:'smooth'})}request()}));
function motionState(){if(!paused&&touring)request();document.body.classList.toggle('motion-paused',paused);toggle.textContent=paused?'RESUME MOTION ▷':'PAUSE MOTION Ⅱ';toggle.setAttribute('aria-pressed',String(paused));last=0;request()}
const tourButton=document.querySelector('#play-tour');tourButton.addEventListener('click',()=>{touring=!touring;if(touring){progress=0;manual=0;tourTime=0;tourStart=performance.now();paused=false;const floor=document.querySelector('.story-floor');floor.classList.add('tour-active');scrollTo({top:journey.offsetTop,behavior:'instant'});motionState()}else{document.querySelector('.story-floor').classList.remove('tour-active')}tourButton.textContent=touring?'STOP WALKTHROUGH □':'PLAY WALKTHROUGH ▷';tourButton.setAttribute('aria-pressed',String(touring));request()});
toggle.addEventListener('click',()=>{paused=!paused;motionState()});reduced.addEventListener('change',()=>{paused=reduced.matches;motionState()});new IntersectionObserver(([e])=>{visible=e.isIntersecting;last=0;request()}).observe(stage);document.addEventListener('visibilitychange',()=>{last=0;request()});resize();renderChapter(0,true);motionState();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));document.body.classList.add('js-motion');
Dexie.liveQuery(()=>db.settings.get('preferences')).subscribe({next:row=>{document.querySelectorAll('[data-store-name]').forEach(e=>e.textContent=row?.value?.store||'A1 TRADERS')},error:()=>{}});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});





