import {db,validateProduct,audit,verifyAudit,money,esc} from './core.js';
import {download} from './receipts.js';
const tables=['products','sales','parked','audit','settings','drafts'];
export async function backupData(){return db.transaction('r',tables.map(t=>db[t]),async()=>Object.assign({version:1,exported:new Date().toISOString()},Object.fromEntries(await Promise.all(tables.map(async t=>[t,await db[t].toArray()])))))}
export async function validateBackup(data){
 if(data?.version!==1||tables.some(t=>!Array.isArray(data[t])))throw Error('Choose a complete A1 TRADERS version 1 backup.');
 for(const t of tables){const keys=new Set();for(const row of data[t]){if(!row||typeof row!=='object')throw Error('Invalid '+t+' record.');const key=row[t==='settings'?'key':'id'];if(!key||keys.has(key))throw Error('Missing or duplicate '+t+' record ID.');keys.add(key)}}
 for(const p of data.products){validateProduct(p);if(typeof p.name!=='string'||!p.sku||!p.barcode)throw Error('Invalid product identity.')}
 const ids=new Set(data.products.map(p=>p.id));
 function lines(rows){if(!Array.isArray(rows))throw Error('Invalid bill items.');for(const l of rows)if(!ids.has(l.id)||typeof l.name!=='string'||!Number.isFinite(l.qty)||l.qty<=0||!Number.isSafeInteger(l.price)||l.price<0||!Number.isFinite(l.tax)||l.tax<0||l.tax>100||!Number.isFinite(l.discount)||l.discount<0||l.discount>100)throw Error('Invalid bill item or missing inventory record.')}
 for(const s of data.sales){lines(s.lines);if(!['completed','cancelled'].includes(s.status)||!Number.isFinite(Date.parse(s.created))||!Number.isSafeInteger(s.total)||s.total<0||!Array.isArray(s.payments)||s.payments.some(p=>!['Cash','Card','UPI','Credit'].includes(p.method)||!Number.isSafeInteger(p.amount)||p.amount<0)||s.payments.reduce((n,p)=>n+p.amount,0)!==s.total)throw Error('Invalid sale or payments.')}
 for(const s of data.sales){let collected=0;for(const c of s.collections||[]){if(!Number.isSafeInteger(c.amount)||c.amount<=0||!['Cash','Card','UPI'].includes(c.method)||!Number.isFinite(Date.parse(c.created)))throw Error('Invalid credit collection.');collected+=c.amount}const originalCredit=s.payments.filter(p=>p.method==='Credit').reduce((n,p)=>n+p.amount,0);let reduced=0;const quantities={};for(const ret of s.returns||[]){if(!Array.isArray(ret.lines)||!Number.isSafeInteger(ret.amount)||ret.amount<0||!Number.isSafeInteger(ret.refund)||ret.refund<0||!Number.isSafeInteger(ret.creditReduction)||ret.creditReduction<0||ret.refund+ret.creditReduction!==ret.amount||!Number.isFinite(Date.parse(ret.created)))throw Error('Invalid return ledger.');reduced+=ret.creditReduction;for(const l of ret.lines){const original=s.lines.find(x=>x.id===l.id);quantities[l.id]=(quantities[l.id]||0)+l.qty;if(!original||!Number.isFinite(l.qty)||l.qty<=0||quantities[l.id]>original.qty+0.000001||!Number.isSafeInteger(l.amount)||l.amount<0)throw Error('Invalid returned quantity.')}}if(collected+reduced>originalCredit)throw Error('Credit ledger exceeds original balance.');}
 for(const s of [...data.parked,...data.drafts]){lines(s.cart);if(!Number.isFinite(s.discount)||s.discount<0||s.discount>100)throw Error('Invalid draft discount.')}
 let previous='GENESIS';for(const {id,hash,...row} of data.audit){if(row.previous!==previous)throw Error('Backup audit chain is broken.');const actual=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(row)))),n=>n.toString(16).padStart(2,'0')).join('');if(actual!==hash)throw Error('Backup audit integrity check failed.');previous=hash}
 return data;
}
export async function restoreData(data,actor){
 await validateBackup(data);
 // Keep a recoverable snapshot outside the tables being replaced.
 const recovery=await backupData();localStorage.setItem('speedbill-before-restore',JSON.stringify(recovery));
 await db.transaction('rw',tables.map(t=>db[t]),async()=>{for(const t of tables){await db[t].clear();await db[t].bulkAdd(data[t])}if(!await Dexie.waitFor(verifyAudit()))throw Error('Audit verification failed. Restore rolled back.');await audit('Backup restored',`Backup from ${data.exported||'unknown date'}`,actor)});
}
export function localDay(date=new Date()){return new Date(date).toLocaleDateString('en-CA')}
export function closingTotals(sales,date,opening=0,expenses=0,refunds=0,counted=0){const rows=sales.filter(s=>localDay(s.created)===date);const payments={Cash:0,Card:0,UPI:0,Credit:0};for(const s of rows)for(const p of s.payments)payments[p.method]=(payments[p.method]||0)+p.amount;for(const s of sales)for(const p of s.collections||[])if(localDay(p.created)===date)payments[p.method]=(payments[p.method]||0)+p.amount;const returns=sales.flatMap(s=>s.returns||[]).filter(r=>localDay(r.created)===date);const recordedCashRefunds=returns.filter(r=>r.method==='Cash').reduce((n,r)=>n+r.refund,0);const expected=opening+payments.Cash-expenses-refunds-recordedCashRefunds;return {date,bills:rows.filter(s=>s.status==='completed').length,cancelled:rows.filter(s=>s.status==='cancelled').length,netSales:rows.filter(s=>s.status==='completed').reduce((n,s)=>n+s.total,0)-returns.reduce((n,r)=>n+r.amount,0),payments,opening,expenses,refunds,recordedCashRefunds,counted,expected,difference:counted-expected}}

export function setupOperations({modal,toast,actor,authorize=async()=>true}){
 let pending=null;
 document.addEventListener('click',async e=>{const a=e.target.closest('[data-op]')?.dataset.op;if(!a)return;try{
 if(a==='backup')download('speedbill-backup-'+localDay()+'.json',JSON.stringify(await backupData(),null,2));
 if(a==='recovery'){const saved=localStorage.getItem('speedbill-before-restore');if(!saved)throw Error('No pre-restore recovery snapshot available.');download('speedbill-before-restore.json',saved)}
 if(a==='restore')modal('Restore backup',`<p class="help">Restore replaces inventory, sales, settings, held bills and the current draft. A recovery copy of current data is kept on this device before replacement.</p><label class="mt-4">A1 TRADERS backup (.json)<input type="file" id="restore-file" accept=".json,application/json"></label><div id="restore-review" class="mt-4"></div><button class="btn mt-4" data-op="recovery">Download previous recovery copy</button>`);
 if(a==='confirm-restore'){if(!await authorize('Restore backup and replace store data'))return;if(!pending)throw Error('Choose a backup first.');if(document.querySelector('#restore-confirm').value!=='RESTORE')throw Error('Type RESTORE to confirm replacement.');const button=e.target.closest('button');button.disabled=true;try{await restoreData(pending,actor());location.reload()}catch(error){button.disabled=false;throw error}}
 if(a==='closing')await closing();
 }catch(error){toast(error.message,true)}});
 document.addEventListener('change',async e=>{try{if(e.target.id==='restore-file'){pending=null;const f=e.target.files[0];if(!f)return;if(f.size>20*1024*1024)throw Error('Backup must be under 20 MB.');const checked=await validateBackup(JSON.parse(await f.text()));pending=checked;document.querySelector('#restore-review').innerHTML=`<div class="notice">Validated: ${checked.products.length} products · ${checked.sales.length} bills · ${checked.audit.length} audit entries.</div><label class="mt-4">Type RESTORE to replace this workspace<input id="restore-confirm" autocomplete="off"></label><button class="btn danger mt-4" data-op="confirm-restore">Replace data and restore</button>`}if(e.target.id==='closing-date')await closing(e.target.value)}catch(error){toast(error.message,true)}});
 async function closing(date=localDay()){
 const saved=(await db.settings.get('closing:'+date))?.value||{};const sales=await db.sales.toArray();
 modal('Daily closing report',`<form id="closing-form"><label>Business date<input id="closing-date" name="date" type="date" value="${esc(date)}" required></label><div class="form-grid mt-4">${[['opening','Opening cash'],['expenses','Cash expenses / withdrawals'],['refunds','Other cash refunds (not recorded in Returns)'],['counted','Cash counted in drawer']].map(([key,label])=>`<label>${label} (₹)<input name="${key}" type="number" min="0" step="0.01" value="${(saved[key]||0)/100}" required></label>`).join('')}</div><label class="mt-4">Expense / refund notes<textarea name="notes" maxlength="1000">${esc(saved.notes||'')}</textarea></label><div id="closing-totals" class="mt-4"></div><p class="help mt-4">Cash receipts include cancelled bills: cancellation does not itself refund cash. Returns recorded in Returns & exchanges are deducted automatically. Enter only additional refunds here to avoid double-counting. Credit collections count on their collection date. Card/UPI figures show recorded receipts before external refunds.</p><div class="modal-actions"><button type="button" class="btn" id="closing-download">Download report</button><button type="submit" class="btn primary">Save closing</button></div></form>`);
 const form=document.querySelector('#closing-form');
 function report(){const fields=Object.fromEntries(new FormData(form));for(const key of ['opening','expenses','refunds','counted']){fields[key]=Math.round(Number(fields[key])*100);if(!Number.isSafeInteger(fields[key])||fields[key]<0)throw Error('Enter valid nonnegative cash amounts.')}return {...closingTotals(sales,date,fields.opening,fields.expenses,fields.refunds,fields.counted),notes:fields.notes}}
 function update(){try{const r=report();document.querySelector('#closing-totals').innerHTML=[['Completed sales',r.netSales],['Cash receipts',r.payments.Cash],['Card receipts',r.payments.Card],['UPI receipts',r.payments.UPI],['Recorded return refunds (cash)',r.recordedCashRefunds],['Credit issued (unpaid)',r.payments.Credit],['Expected drawer cash',r.expected],['Counted minus expected',r.difference]].map(([label,n])=>`<div class="summary-row"><span>${label}</span><strong>${money(n)}</strong></div>`).join('')}catch{}}
 form.addEventListener('input',update);update();
 form.addEventListener('submit',async e=>{e.preventDefault();try{if(!form.reportValidity())return;const r=report();await db.transaction('rw',db.settings,db.audit,async()=>{await db.settings.put({key:'closing:'+date,value:{...r,saved:new Date().toISOString(),cashier:actor()}});await audit('Daily closing saved',`${date} · expected ${money(r.expected)} · counted ${money(r.counted)} · difference ${money(r.difference)}`,actor())});toast('Daily closing saved.')}catch(error){toast(error.message,true)}});
 document.querySelector('#closing-download').onclick=()=>{try{if(!form.reportValidity())return;download('daily-closing-'+date+'.json',JSON.stringify(report(),null,2))}catch(error){toast(error.message,true)}};
 }
}

